project_id = "main-street-media-client-portal"

[api]
enabled = true
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"
